[versions]
kotlin = "1.9.23"

[libraries]
cognitoidentityprovider = {module = "aws.sdk.kotlin:cognitoidentityprovider", version = "1.2.10"}

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.6" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
